f = open('w.txt', 'w')
f.write('Hello, World!!!\nhello, Python!!!\nhello, Python!!!\nhello, Python!!!\nhello, Python!!!')
f.close()
f= open('w.txt', 'r')
f.readline()
z = f.tell()
f.seek(z-1)
print(f.read(1))
print(f.read(1))