import pickle
import csv
f = open('w.txt', 'w')
f.write('Hello, World!!!\nhello, Python!!!\nhello, Python!!!\nhello, Python!!!\nhello, Python!!!')
f.close()
f= open('w.txt', 'r')
f.readline()
z = f.tell()
f.seek(z-1)
print(f.read(1))
print(f.read(1))
f.close()
f = open('w.csv','w',newline='')
writer = csv.writer(f, delimiter='|')
writer.writerow(['rajdeep', 'sarkar', '23'])
di = csv.DictWriter(f, fieldnames=['name', 'surname', 'age'], delimiter='|')
D = {'name':'rajdeep', 'surname':'sarkar', 'age':'23'}
di.writeheader()
di.writerow(D)
f.close()
f = open('w.csv','r')
reader = csv.reader(f, delimiter='|')
for row in reader:
    print(row)
f.close()